# Generated by Django 6.0 on 2026-02-20 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artworks', '0002_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at'], 'verbose_name': 'Artwork', 'verbose_name_plural': 'Artworks'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at'], 'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='autor',
            field=models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='autor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='descripcion',
            field=models.TextField(blank=True, db_column='descripcion', default='', null=True),
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='generos',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='imagen',
            field=models.ImageField(db_column='imagen', help_text='Imagen de la obra (máximo 10MB)', upload_to='artworks/'),
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='imagen',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='likes',
            field=models.IntegerField(db_column='likes', default=0),
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='likes',
            new_name='like_count',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='titulo',
            field=models.CharField(db_column='titulo', max_length=200),
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, db_column='fecha_actualizacion'),
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='vistas',
            field=models.IntegerField(db_column='vistas', default=0),
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='vistas',
            new_name='view_count',
        ),
        migrations.AlterField(
            model_name='genre',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='genre',
            name='descripcion',
            field=models.TextField(blank=True, db_column='descripcion', default='', null=True),
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='genre',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=100, unique=True),
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='like',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.RenameField(
            model_name='like',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='like',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='like',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('artwork', 'user')},
        ),
    ]
