# Generated by Django 6.0 on 2026-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_add_profile_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-is_superuser', 'is_active', 'email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_creacion'),
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(blank=True, db_column='nombre', default='', max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='nombre',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='apellidos',
            field=models.CharField(blank=True, db_column='apellidos', default='', max_length=50, null=True),
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='apellidos',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, db_column='fecha_actualizacion'),
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='imagen_perfil',
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, db_column='descripcion', default='', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, db_column='imagen_perfil', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If disabled, the user cannot access their account', verbose_name='Is active?'),
        ),
    ]
